extends Node2D
var Dialogue
var BoxColor
var Roles
func _ready():
	BoxColor = Color(0.5,1,0.5,1)
	Roles = [
		"character_egorich def",
		"character_lentoln jud",
		#"character_temich hld",
		"character_sonya pro",
		"character_sewa wit",
		"character_temich wit",
		"character_tuvok wit",
		"character_msis wit",
	]
	Dialogue = [ # диалоги. 
		"Егорыч: ...",
		"(Это - финал.)|B|character_egorich thinks",
		"Елена Анатольевна, у меня сохранились сведения о графине, в котором нам был подан лимонад. А также о стаканах.|W|character_egorich paper|START logic",
		"Графин был литровым, в нем был подан лимонад. Стаканы же имели объём 250 мл.|W|character_egorich thinks|---|---|show grafin",
		"Тёмыч: Если бы пятеро человек выпило по стакану лимонада из этого графина, то в конце объём лимонада в графине составлял бы -250 мл.|W|character_temich kekk",
		"Е. Анатольевна: Что это значит?|W|character_lentoln hmm",
		"Егорыч: Варианты таковы:|G|character_egorich thinks|---|---|split;Стаканы имели объём 200 мл:7;В графине было 1250 мл лимонада:13;Стаканов было четверо.:24",
		"Стаканы были всё-таки по 200 мл.|W|character_egorich yee",
		"OBJECTION obj wv ",
		"Тёмыч: В могилу меня сведешь, Егорыч. Мы вдвоём лично посчитали объёмы стаканов, применив пре-калькулус.|W|character_temich deskslam|---|REACT slam",
		"Егорыч: А, точно.|W|character_egorich all_of_sudden",
		"Тёмыч: Думай, Егогорыч, Думай!|W|character_temich dadada",
		"JUMP 6",
		"Егорыч: В графине было больше лимонада, чем мы думали. Его и хватило на пятого человека.|W|character_egorich yee",
		"Соня: Значит, показания свидетеля полностью валидные.|Y|character_sonya death",
		"Егорыч: Да.|W|character_egorich suspects",
		"Соня: А значит, Зинец виновен.|Y|character_sonya death",
		"Егорыч: ...|W|character_egorich all_of_sudden",
		"OBJECTION obj wv ",
		"Тёмыч: Лентольна, можно Егорыча пнуть?|W|character_temich kekk",
		"Е. Анатольевна: Ну, вообще не стоит|W|character_lentoln hmm",
		"Но за такое, в плане 'зуб за зуб', можно простить попытаться.",
		"Егорыч: Не надо! Не надо! Я понял! Я исправлюсь!|W|character_egorich all_of_sudden",
		"JUMP 6",
		"Егорыч: Это означает, что четверо человек в тот момент 'пило' лимонад!|W|character_egorich slam|STOP all|REACT slam",
		"Тёмыч: А следовательно, Жека - пятая лишняя!|W|character_temich kekk|START pursuit|---",
		"Жека: Ч-Что?! Откуда я знала, что вы записали этот сраный графин в свои сраные записи?!|W|character_msis what",
		"Тёмыч: А что такое? Не ожидала?|W|character_temich kekk",
		"Было алиби, да всплыло: возвращаемся к вопросу маскировки в араба.|W|character_temich deskslam|---|REACT slam",
		"Беркут: Да что вы заладили? Вяжите лучше Зинца, у него же стопку денег нашли!|W|character_sewa rage",
		"Егорыч: Ты кстати так и не показал нам историю транзакций. На этот раз не будет возражений, Сонич?|W|character_egorich slam|---|REACT slam",
		"Соня: ...Нет.|Y|character_sonya death",
		"Е. Анатольевна: А суд будет настаивать на этом, на этот раз.|W|character_lentoln hmm",
		"Тёмыч: Кстати, на этом хиджабе ведь остались отпечатки пальцев или пото-жировые следы?|W|character_temich kekk",
		"Лентольна, давайте внеочередную лабораторку проведем.|W|character_temich dadada",
		"'Судмедэкспертизу'",
		"Жека: В смысле?|W|character_msis ugh",
		"Егорыч: Видите ли, если мы увидим историю транзакций Беркута и докажем, что хиджаб действительно Жекин|W|character_egorich thinks",
		"То это будет занавес.|W|character_egorich suspects",
		"Беркут: Я не дам свой телефон! Вы не добьётесь!|W|character_sewa rage|STOP all",
		"Тёмыч: В таком случае, попросим *дядю полицейского*|R|character_temich default",
		"Егорыч: И тётю патологоанатома!|W|character_egorich yee",
		"Тёмыч: Это немного другое, но ладно.|W|character_temich kekk",
		"В любом случае, твоя свобода приказала долго существовать.",
		"До свидания.|R|character_temich objection_1|---|REACT intro_woosh",
		"Всего доброго!|R|character_egorich objection|---|REACT intro_woosh",
		"Беркут: ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...|W|character_sewa death1",
		"НЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕТ!!!!!!!|W|character_sewa death2|---|REACT sith_slam",
		"Егорыч: ...|W|character_egorich all_of_sudden|---|REACT surprise",
		"Тёмыч: Вот так вот...|W|character_temich comeon|REACT surprise",
		"Соня: ...|W|character_sonya death|REACT surprise",
		"Е. Анатольевна: ...|W|character_lentoln omg|REACT surprise",
		"Ну, мне всё ясно.|W|character_lentoln sigh|START verdict",
		"Дело обещало быть значительно более продолжительным, но этих улик и манипуляций свидетелями оказалось достаточно.",
		"Что могу сказать, если бы вы сохраняли спокойствие, пока-что-свидетели, то вас бы никто и не раскрыл.",
		"Жека: Это еще не всё! Не думай, что ты так просто выберешься из грязи, Зинец!|W|character_msis rage",
		"Тёмыч: Не думай, что ты когда-либо отмоешь от помоев хотя бы квадратный сантиметр своей репутации!|W|character_temich kekk",
		"А с тем темпом, с которым ты проваливаешь задания Дашкерина, то и на то, что ты когда-либо съедешь от своего полубати.",
		"Пускай ты навсегда останешься под одной крышей с ним, брошенной на произвол судьбы, без единого верного друга, который вступится за тебя!|W|character_temich objection_1|---|REACT intro_woosh",
		"Жека: ЭЭЭЙ!!!! НЕТ!|W|character_msis rage",
		"Егорыч: (Сильно сказано.)|B|character_egorich suspects",
		"Е. Анатольевна: Обвиняемый в массовых карманных кражах, Артём Зинец, отныне считается в содеянном...|W|character_lentoln kek",
		"Невиновным|BIG",
		"На этом всё, судебное заседание объявляется закрытым.|W",
	]
