extends Node2D
var Dialogue
var BoxColor
var Roles
func _ready():
	BoxColor = Color(0.5,1,0.5,1)
	Roles = [
		"character_egorich def",
		"character_lentoln jud",
		#"character_temich hld",
		"character_sonya pro",
		"character_sewa wit",
		"character_temich wit",
	]
	Dialogue = [ # диалоги. 
		"",
		"Егорыч: Елена Анатольевна, в показаниях Тьохи есть противоречие!|W|character_egorich yee",
		"Тёмыч: И довольный такой|W|character_temich kekk",
		"Е. Анатольевна: И как же так?|W|character_lentoln hmm",
		"Егорыч: Тьоха говорит, что его карманы были пусты.|W|character_egorich paper",
		"Однако, Тьоха, не из твоего ли кармана...|W|character_egorich slam|---|REACT slam",
		"...вывалилась эта стопка?|W|character_egorich objection|---|REACT intro_woosh|show money",
		"Тёмыч: А!|W|character_temich damn|START egorich_objection|---",
		"Так... Это ж не из моего кармана!|W|character_temich rage",
		"Я напомню, что когда я выворачивал свои карманы, чтобы доказать, что чужих денег у меня нет,",
		"Эти деньги, да, выпали из того места, где у меня карманы.",
		"Но готов поклясться, что в этот же момент кто-то был рядом со мной и выбросил эту стопку",
		"В силу перспективы и прочей хрени показалось, что это из меня выпало. Но это мне подбросили!|W|character_temich kekk",
		"OBJECTION obj",
		"Соня: Кто|Y|character_sonya death",
		"Егорыч: Ну, кто-то, кто был рядом с Тьохой.|W|character_egorich thinks",
		"Соня: Кто|Y|character_sonya death",
		"Егорыч: (Видимо, она хочет, чтобы я назвал человека.)|B|character_egorich suspects",
		"(Но откуда я знаю? ...Странно, но я бы точно заметил, что кто-то подбрасывает Тьохе деньги!)|B",
		"(...Должно быть объяснение, иначе Тьоха - виновен.)",
		"Е. Анатольевна: То есть, ты хочешь сказать, что эти деньги тебе подбросили?|W|character_lentoln hmm",
		"Тёмыч: Нет, блин, это я их стырил и они у меня выпали, что теперь я пытаюсь отмазаться.|W|character_temich kekk",
		"Соня: ...|W|character_sonya death",
		"Егорыч: Спокойно, спокойно! Не надо выдвигать на этом протест, дорогая моя!|W|character_egorich all_of_sudden",
		"А ты, Тьоха, думай, что говоришь. Это вполне могла расценить Лентольна как признание в содеянном.",
		"Тёмыч: Ой всё...|W|character_temich comeon",
		"Соня: ...|W|character_sonya death|STOP all",
		"И кто же их подкинул?|Y|character_sonya death|START theme_of_sith",
		"Егорыч: Я... не знаю.|W|character_egorich thinks",
		"Соня: В таком случае, украденные деньги выпали конкретно из кармана Тёмыча|Y|character_sonya death",
		"Егорыч: (Черт, она права.)|B|character_egorich rage",
		"(Если я не могу показать, кто подкинул Тьохе деньги, то подозреваемым будет только Тьоха...)",
		"(Чёрт.)",
		"Соня: Приплыли.|Y|character_sonya death",
		"Е. Анатольевна: Соня права, тут нужны доказательства хотя бы... А то, как деньги выпали из Артёма, видела даже я.|W|character_lentoln sigh",
		"Соня: Деньги выпали из Тёмыча, это все видели.|Y|character_sonya death",
		"Кто, если не он, украл их?",
		"OBJECTION obj wv egor",
		"Егорыч: Тогда объясни уже мне другое противоречие.|W|character_egorich slam|---|REACT slam",
		"В этих деньгах есть и моя доля. Ты думаешь, что Тьоха украл бы мои деньги?|W|character_egorich paper|---|---|show money",
		"Деньги своего лучшего друга?!",
		"Соня: ...|W|character_sonya death",
		"1-1.|Y",
		"Егорыч: То-то же.|W|character_egorich yee",
		"(Действительно, Тьохе кто-то подкинул эти деньги. И если я покажу как, либо кто, то я выиграю дело)|B",
		"Е. Анатольевна: Как у вас всё завернулось. Ладно, ещё вопросы к Тьохе есть?|W|character_lentoln default|STOP all",
		"Тёмыч: Лентольна, меня зовут Артём.|W|character_temich kekk",
		"Е. Анатольевна: Ну да, Тьоха...|W|character_lentoln default",
		"Ой, то есть... Пообщайся с вами еще и начнёшь кричать 'Протестую!'|W|character_lentoln omg",
		"Соня: Беркут. Одна из жертв Тёмыча.|Y|character_sonya death",
		"Тёмыч: Презумпция невиновности была успешно послана на...|W|character_temich kekk",
		"...половчан, на кобяка.|W|character_temich dadada",
		"Е. Анатольевна: Ясно. Что же, Захара Беркута сюда.|W|character_lentoln default",
		"Тёмыч: Я, наверное, покину зал суда, потому что вы уже все мои шутки переняли и даже свои придумываете.|W|character_temich yee",
		"Е. Анатольевна: В смысле?|W|character_lentoln omg",
		"Соня: Свидетеля зовут *Всеволод* Беркут|Y|character_sonya death",
		"Е. Анатольевна: А, ой...|W|character_lentoln omg",
		"Эх...|W|character_lentoln sigh",
		"просто зовите его уже, ради бога.",
		"Беркут: Здравствуйте.|W|character_sewa oi|START enterwit",
		"Соня: Имя, профессия.|Y|character_sonya death",
		"Беркут: А ты типа не знаешь.|W|character_sewa kaef",
		"Соня: ...|W|character_sonya death|STOP all",
		"Как ты меня достал...|Y",
		"Ты думаешь, что ты можешь со мной играться?",
		"Беркут: ...|W|character_sewa oi",
		"Соня: Ты мне надоел.|Y|character_sonya death",
		"Ты постоянно орёшь, при том матом",
		"У меня от тебя болят уши.",
		"Беркут: ...|W|character_sewa oi",
		"Соня: А задай тебе простейший вопрос, так ты будешь выкаблучиваться.|Y|character_sonya death",
		"Судья|R",
		"Свидетеля зовут *Ирод Окаянный*|Y",
		"И он - паркурщик.",
		"Беркут: ЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭ!!!!!!!!|W|character_sewa rage|START enterwit",
		"Я, вообще-то, трейсер!",
		"И меня зовут Всеволод Беркут и я из 9-В класса!",
		"Соня: Сразу бы так.|Y|character_sonya death",
		"Егорыч: (Так тактично еще никто не добывал из свидетеля имя-профессию!)|B|character_egorich all_of_sudden",
		"Соня: Что ты знаешь о деле.|Y|character_sonya death",
		"Беркут: Че-то ты раскудахталась, курица!|W|character_sewa rage",
		"Соня: ...|W|character_sonya death",
		"Беркут: ...|W|character_sewa oi",
		"Егорыч: Я советую тебе бежать.|W|character_egorich yee",
		"Тёмыч: Мой друг, я тебе посекрету скажу|W|character_temich yee",
		"Из окна падать не так уж и больно|W|character_temich kekk",
		"Соня: ...|W|character_sonya death",
		"Е. Анатольевна: Я не одобряю насилия в от детей сторону детей|W|character_lentoln hmm",
		"Но зная характер Сони, вот это вот её текущее молчание очень неестественно.|W|character_lentoln hmm",
		"У нас, конечно, убивать запрещено",
		"Но после того, что ты сказал, её вряд ли остановит панцеркампфваген IV, не то, что какой-то там закон...",
		"Если выпьешь метиловый спирт, то не будешь видеть того, что она с тобой сделает.",
		"Соня: ...|W|character_sonya death",
		"...|W|character_sonya forceslam|---|REACT sith_slam",
		"Егорыч: А!|W|character_egorich all_of_sudden",
		"Соня: Ой, трещина пошла.|Y|character_sonya death",
		"Прошу прощения.",
		"Егорыч: Севыч, ради бога|W|character_egorich thinks",
		"Беркут: ...|W|character_sewa oi",
		"Егорыч: Другого шанса она тебе не даст.|W|character_egorich thinks",
		"(Как Тьоха с ней управляется, вообще?)|B",
		"Беркут: ...Я просто расскажу свои показания и всё.|W|character_sewa default|STOP all",
		"--- Меня ограбили ---|R|character_sewa default|---|REACT intro_woosh",
		"Беркут: Какая-то сволочь украла у меня мои кровные деньги. 500!|W|character_sewa rage|START examination-moderato|REACT damage",
		"Беркут: У моей девушки, уже бывшей, кстати, тоже. Не знаю, сколько именно.|W|character_sewa default",
		"Беркут: Вчера в музее хренороба мы с девушкой гуляли одни и отвлеклись.|W|character_sewa oi",
		"Беркут: В этот момент, Зинец и ограбил нас, пока мы его не видели!|W|character_sewa rage",
		"Е. Анатольевна: Егор, начинай.|W|character_lentoln default|STOP all",
		"Егорыч: (Это будет просто. Во всяком случае, так говорит Тёмыч перед каждым допросом.)|B|character_egorich yee",
		"(...Ладно, может не просто. А может... Не знаю, короче.)|B|character_egorich suspects",
		"OUT res://scenes/case_3/trial_1/trial_4_interogate.tscn",
	]
