extends Node2D
var Anims
var Dialogue
var Ev
var Music
var loc_file = ConfigFile.new()
var Cast
func _ready():
	Dialogue = [ # диалоги. 
		"",
		"Соня: ... ",
		"Тёмыч: ...",
		"Е. Анатольевна: ...",
		"Егорыч: Чего сидим, кого ждем?",
		"Тёмыч: Свида, кого еще...",
		"Где этого черта носит?",
		"Соня: ...",
		"Е. Анатольевна: Свидетелем обвинение объявило Башима Дашкерина",
		"Он из 10-Г класса, а у них я химию веду.",
		"Он всегда опаздывает, причем серьезно",
		"На 5 минут, 10...",
		"Тёмыч: Закончим сегодня по-раньше, ха.",
		"В. Юрьевна: Пришел, Лен!",
		"Е. Анатольевна: Запускай.",
		"???: Привет ребятки, как дела?",
		"Тёмыч: (Ляха, перелогинься с основы.) B",
		"Соня: Анкета. Y", # дамаг
		"Дашкерин: Башим Дашкерин, крутой парень с 10-Г класса, да... W",
		"Тёмыч: (Артём Зинец, чертила та еще с 8-В.) B",
		"(Интересно, если бы я был свидом, как бы я себя вел...?)",
		"Соня: Что произошло. Y",
		"Дашкерин: Оу май гад, такая кул стори, я её залил в инсту. W",
		"Е. Анатольевна: Стоп, что? У тебя есть какая-то запись, которую ты выложил в интернет?",
		"Дашкерин: О да, я получил кучу подписчиков под свой аккаунт.",
		"Аж 100",
		"Е. Анатольевна: Ну и ну, мне теперь это все разгребать придется...",
		"Тёмыч: Лентольна, 100 человек тех тырнетах, это как 1 человек со всего Запижорья. Из семи миллиардов людей, 100 человек должно иметь тесные связи с нашим, скажем так, 'окружением'",
		"Так что разгребать долго не придется.",
		"Дашкерин: Да что ты понимаешь в инстаграме, смерт?",
		"Тёмыч: Ну если для тебя 100 подписчиков это очень много...",
		"Вообще ничего, хах!",
		"Соня: ...",
		"Тёмыч: А, всё, больше не отвлекаю. Показания бренных свидов это святое.",
		"Соня: ...",
		"OUT ",
	]
	Anims = [ # диалоги. 
		"",
		"character_sonya death Соня: ... POS pro",
		"character_temich picard Тёмыч: ... POS def",
		"character_lentoln sigh Е. Анатольевна: ... POS jud",
		"character_egorich thinks Егорыч: Чего сидим, кого ждем? POS hld",
		"Тёмыч: Свида, кого еще...",
		"character_temich kekk де этого черта носит? POS def",
		"character_sonya default Соня: ... POS pro",
		"character_lentoln default Е. Анатольевна: Свидетелем обвинение объявило Башима Дашкерина POS jud",
		"Он из 10-Г класса, а у них я химию веду.",
		"character_lentoln rage Он всегда опаздывает, причем серьезно",
		"На 5 минут, 10...",
		"character_temich wonder Тёмыч: Закончим сегодня по-раньше, ха. POS def",
		"character_lentoln hmm В. Юрьевна: Пришел, Лен! POS jud",
		"character_lentoln kek Е. Анатольевна: Запускай.",
		"character_wit default ???: Привет ребятки, как дела? POS wit",
		"character_temich picard Тёмыч: (Ляха, перелогинься с основы.) B POS def",
		"character_sonya damage Соня: Анкета. Y POS pro", # дамаг
		"character_wit default Дашкерин: Башим Дашкерин, крутой парень с 10-Г класса, да... W POS wit",
		"character_temich thonker Тёмыч: (Артём Зинец, чертила та еще с 8-В.) B POS def",
		"(Интересно, если бы я был свидом, как бы я себя вел...?)",
		"character_sonya death Соня: Что произошло. Y POS pro",
		"character_wit zomg Дашкерин: Оу май гад, такая кул стори, я её залил в инсту. W POS wit", # нада нарисовать онимку ыыыыыы
		"character_lentoln rage Е. Анатольевна: Стоп, что? У тебя есть какая-то запись, которую ты выложил в интернет? POS jud",
		"character_wit yee Дашкерин: О да, я получил кучу подписчиков под свой аккаунт. POS wit", # опять таки
		"character_wit zomg Аж 100",
		"character_lentoln sigh characterЕ. Анатольевна: Ну и ну, мне теперь это все разгребать придется... POS jud",
		"character_temich wonder Тёмыч: Лентольна, 100 человек тех тырнетах, это как 1 человек со всего Запижорья. Из семи миллиардов людей, 100 человек должно иметь тесные связи с нашим, скажем так, 'окружением' POS def",
		"character_temich kekk Так что разгребать долго не придется. POS def",
		"character_wit zomg Дашкерин: Да что ты понимаешь в инстаграме, смерт? POS wit",
		"character_temich dadada Тёмыч: Ну если для тебя 100 подписчиков это очень много... POS def",
		"character_temich kekk Вообще ничего, хах! POS def",
		"character_sonya death Соня: ... POS pro",
		"character_temich kekk Вообще ничего, хах! POS def",
		"character_sonya death Соня: ... POS pro",
		"OUT ",
	]
	Music = [ # диалоги. 
		"",
		"START peaceful_day character_sonya death Соня: ... POS pro",
		"REACT frustration character_temich picard Тёмыч: ... POS def",
		"REACT surprise character_lentoln sigh Е. Анатольевна: ... POS jud",
		"character_egorich thinks Егорыч: Чего сидим, кого ждем? POS hld",
		"Тёмыч: Свида, кого еще...",
		"REACT surprise character_temich kekk де этого черта носит? POS def",
		"REACT frustration character_sonya default Соня: ... POS pro",
		"character_lentoln default Е. Анатольевна: Свидетелем обвинение объявило Башима Дашкерина POS jud",
		"Он из 10-Г класса, а у них я химию веду.",
		"REACT damage character_lentoln rage Он всегда опаздывает, причем серьезно",
		"На 5 минут, 10...",
		"character_temich wonder Тёмыч: Закончим сегодня по-раньше, ха. POS def",
		"STOP character_lentoln hmm В. Юрьевна: Пришел, Лен! POS jud",
		"character_lentoln kek Е. Анатольевна: Запускай.",
		"START enterwit character_wit default ???: Привет ребятки, как дела? POS wit",
		"character_temich picard Тёмыч: (Ляха, перелогинься с основы.) B POS def",
		"character_sonya damage Соня: Анкета. Y POS pro", # дамаг
		"character_wit default Дашкерин: Башим Дашкерин, крутой парень с 10-Г класса, да... W POS wit",
		"character_temich thonker Тёмыч: (Артём Зинец, чертила та еще с 8-В.) B POS def",
		"(Интересно, если бы я был свидом, как бы я себя вел...?)",
		"character_sonya death Соня: Что произошло. Y POS pro",
		"character_wit zomg Дашкерин: Оу май гад, такая кул стори, я её залил в инсту. W POS wit", # нада нарисовать онимку ыыыыыы
		"character_lentoln rage Е. Анатольевна: Стоп, что? У тебя есть какая-то запись, которую ты выложил в интернет? POS jud",
		"character_wit yee Дашкерин: О да, я получил кучу подписчиков под свой аккаунт. POS wit", # опять таки
		"character_wit zomg Аж 100",
		"character_lentoln sigh characterЕ. Анатольевна: Ну и ну, мне теперь это все разгребать придется... POS jud",
		"character_temich wonder Тёмыч: Лентольна, 100 человек тех тырнетах, это как 1 человек со всего Запижорья. Из семи миллиардов людей, 100 человек должно иметь тесные связи с нашим, скажем так, 'окружением' POS def",
		"character_temich kekk Так что разгребать долго не придется. POS def",
		"character_wit zomg Дашкерин: Да что ты понимаешь в инстаграме, смерт? POS wit",
		"character_temich dadada Тёмыч: Ну если для тебя 100 подписчиков это очень много... POS def",
		"character_temich kekk Вообще ничего, хах! POS def",
		"character_sonya death Соня: ... POS pro",
		"character_temich kekk Вообще ничего, хах! POS def",
		"character_sonya death Соня: ... POS pro",
		"OUT ",
	]
	loc_file.load("C:/Games/ddkg2.save")
	loc_file.set_value("Locations","Last",filename)
	loc_file.save("C:/Games/ddkg2.save")
